default: &default
  adapter: mysql2
  encoding: utf8
  pool: 10
  protocol: tcp
  url: <%= ENV.fetch('DATABASE_URL') { "mysql2://#{ENV.fetch('DATABASE_USERNAME') { 'root' }}:#{ENV.fetch('DATABASE_PASSWORD') { 'root' }}@#{ENV.fetch('DATABASE_HOST') { 'db' }}:#{ENV.fetch('DATABASE_PORT') { 3306 }}" } %>
  # username: <%= ENV.fetch('DB_USERNAME') { 'root' } %>
  # password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  # host: <%= ENV.fetch('DB_HOST') { 'db' } %>
  # port: 3306

development:
  <<: *default
  database: draw_dev

test:
  <<: *default
  database: draw_test

production:
  <<: *default
  database: draw_production


